name: dio_cache
description: A plugin for dio that caches responses for better optimization and offline data access.
version: 0.1.2-beta
homepage: https://github.com/aloisdeniel/dio_cache
author: aloisdeniel <alois.deniel@outlook.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  meta: ^1.1.6
  logging: ^0.11.3
  dio: ^2.1.7
  path: ^1.6.2
  uuid: ^2.0.2

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
